{name:"Jiwaki", id:"bonito"},
{name:"Ñaxu, ist’ara", id:"feo, horrible"},
{name:"Muxsa, musq’a", id:"dulce"},
{name:"Jaru, jaxu", id:"amargo"},
{name:"Phisna", id:"liviano"},
{name:"Jathi", id:"pesado"},
{name:"Jach’a", id:"grande"},
{name:"Jisk’a", id:"chico"},
{name:"Phuqa", id:"lleno"},
{name:"Ch’usa, q’ala", id:"vacío"},
{name:"K’ara", id:"salado"},
{name:"Laq’a, ch’apaqa", id:"desabrido"},
{name:"Quña", id:"suave"},
{name:"Chhama, qhulu", id:"áspero, duro"},
{name:"Siq’i", id:"delgado"},
{name:"Lankhu", id:"grueso"},
{name:"Junt’u", id:"caliente"},
{name:"Ch’uñuri", id:"frío"},
{name:"Q’uma", id:"limpio"},
{name:"Ch’ixlli", id:"sucio"},
{name:"Machaca", id:"nuevo"},
{name:"Thantha, mirq’i", id:"usado, viejo"},
{name:"Waña", id:"seco"},
{name:"Juri", id:"mojado"},
{name:"Alluxa, walxa", id:"harto"},
{name:"Juk’a", id:"poco"},
{name:"Jak’a", id:"cerca"},
{name:"Jaya", id:"lejos"},
{name:"Lik’i", id:"gordo"},
{name:"Thuk’a", id:"flaco"},
{name:"Qhupu", id:"ancho"},
{name:"K’ullk’u", id:"angosto"},
{name:"Khusa, suma", id:"bueno"},
{name:"Ñaxu", id:"malo"},
{name:"Jayra", id:"flojo"},
{name:"P’iqini, ch’iqi", id:"inteligente"},
{name:"Thuskha", id:"hediondo"},
{name:"T’amata, ñusata", id:"podrido, fermentado"},
{name:"Paxpuru", id:"pícaro"},
{name:"Mich’a", id:"ávaro, codicioso"},
{name:"Qhaxu", id:"molestoso"},
{name:"Llawlli", id:"charlatán"},
{name:"Jachawalla", id:"llorón"},
{name:"Kusisita", id:"alegre"}