{name:"Lixwi", id:"seso"},
{name:"Ajanu, uñaqa", id:"cara, rostro"},
{name:"P’iqi", id:"cabeza"},
{name:"Para", id:"frente"},
{name:"Illpa", id:"sien"},
{name:"Nak’uta, lak’uta", id:"pelo"},
{name:"Nayra", id:"ojo"},
{name:"Nayra Phichu", id:"ceja"},
{name:"Nasa", id:"nariz"},
{name:"Jinchu", id:"oreja"},
{name:"Laka", id:"boca"},
{name:"Laka ch’akha", id:"diente"},
{name:"Jipsi, ispi", id:"labio"},
{name:"Aqu, k’ama", id:"muela"},
{name:"Laxra", id:"lengua"},
{name:"Thusunqaya", id:"saliva"},
{name:"Llawsa", id:"baba"},
{name:"Linphu", id:"vello"},
{name:"Sunkha, chunkha", id:"barba o bigote"},
{name:"K’ana", id:"trenza"},
{name:"Ati, kukusa", id:"nuca"},
{name:"Ampara", id:"mano"},
{name:"Luk’ana", id:"dedo"},
{name:"Sillu", id:"uña"},
{name:"Mujlli", id:"codo"},
{name:"Lli-lli", id:"axila"},
{name:"Jikhana", id:"espalda"},
{name:"Kallachi", id:"hombro"},
{name:"Jaraphi", id:"costilla"},
{name:"Muqu", id:"articulación, codo"},
{name:"Chuyma", id:"corazón (sentimiento)"},
{name:"Lluqu", id:"corazón (víscera)"},
{name:"Kururu", id:"ombligo"},
{name:"Puraka, puraja", id:"estómago"},
{name:"Maymuru", id:"riñón"},
{name:"K’iwcha", id:"hígado"},
{name:"Thixni", id:"cadera"},
{name:"Jiphilla", id:"tripas, intestinos"},
{name:"Anku", id:"nervio"},
{name:"Ch’akha", id:"hueso"},
{name:"Chara", id:"pierna"},
{name:"Lankhu chara", id:"muslo"},
{name:"Qunquri", id:"rodilla"},
{name:"T’usu", id:"pantorilla"},
{name:"Kayu", id:"pie"},
{name:"Wintu", id:"talón "},
{name:"Ñuñu", id:"tetilla o senos"},
{name:"Ch’ina", id:"glúteo, trasero"},
{name:"Chinqi", id:"vagina"},
{name:"Allu", id:"pene"},
{name:"Q’uruta", id:"testículo"},
{name:"Ch’uxu", id:"orina"},
{name:"Jama", id:"excremento"},
{name:"Jamaña", id:"recto"},
{name:"Wila", id:"sangre"}, 
{name:"Ajayu, amaya", id:"espíritu"}