{name:"Chacha",id:"hombre"},
{name:"Warmi",id:"mujer, esposa"},
{name:"Tata",id:"señor, padre"},
{name:"Mama",id:"señora, madre"},
{name:"Awki",id:"padre"},
{name:"Tayka",id:"madre"},
{name:"Jach’a tata",id:"abuelo"},
{name:"Jach’a mama",id:"abuela"},
{name:"Achachi",id:"viejo (despectivo)"},
{name:"Apachi",id:"vieja (despectiva)"},
{name:"Jila, Jilata",id:"hermano"},
{name:"Kullaka, Kullall",id:"hermana"},
{name:"Yuqalla",id:"niño"},
{name:"Imilla",id:"niña"},
{name:"Wayna",id:"joven varón"},
{name:"Tawaqu",id:"joven dama (srta.)"},
{name:"Allchi",id:"nieto(a)"},
{name:"Tullqa",id:"yerno"},
{name:"Yuxch’a",id:"nuera"},
{name:"Ichutata",id:"padrino"},
{name:"Ichumama",id:"madrina"},
{name:"Wajcha",id:"huérfano"},
{name:"Munata",id:"querido(a)"},
{name:"Jiliri",id:"hno. Mayor"},
{name:"Sullkiri",id:"hno. Menor"},
{name:"marka masi",id:"paisano(a), Coterráneo."}