{name:"tunka", id:10, color:"bg-light-blue",check:null},
{name:"Jila, Jilata", id:"hermano"},
{name:"Uru", id:"día"},
{name:"Kullaka", id:"hermana"},
{name:"Phaxsi", id:"luna, mes"},
{name:"Yuqalla", id:"niño"},
{name:"Mara", id:"año"},
{name:"Imilla", id: "niña"},
{name:"Jisa", id: "sí"},
{name:"Chacha", id: "hombre"},
{name:"Jani, Janiwa", id:"no"},
{name:"Warmi", id:"mujer"},
{name:"Qhalt’i", id: "mañana"},
{name:"Mama", id: "señora"},
{name:"Jayp’u", id: "tarde"},
{name:"Tata", id: "señor"},
{name:"Arama, aruma", id: "noche"},
{name:"Yatichiri", id: "profesor (a)"},
{name:"Masuru", id: "ayer"},
{name:"Yatintiri", id: "alumno (a)"},
{name:"Jichhüru", id: "hoy día"},
{name:"Yatiqiri", id: "alumno (a)"},
{name:"Kama",id: "hasta (sufijo)"},
{name:"Naka, naja", id: "suf. Pluralizador"},
{name:"T’ant’a", id: "pan"},
{name:"Munata", id: "querido (a)"},
{name:"Jayu", id: "sal"},
{name:"Yuspayarpa", id: "gracias"},
{name:"Maq’a", id: "comida"},
{name:"Waqt’ita",id: "regálame"},
{name:"Aycha", id: "carne"},
{name:"Past’ita", id: "pásame (prést)"},
{name:"K’awna", id: "huevo"},
{name:"Jutma, Jútam", id: "ven"},
{name:"Ch’uqi", id: "papa"},
{name:"Tukuytati", id: "¿terminaste?"},
{name:"Tukuyapxtati", id: "¿han terminado?"}